### ISSUE TITLE
Uno.Net does not contain type or namespace 'Sockets'.

### ISSUE THREAD

**Issue by ZOITK** [solisoft/FuseSocketTCP#1]
`sock.uno(7.15): E3111: Uno.Net does not contain type or namespace 'Sockets'. Cou
ld you be missing a package reference?`
`sock.uno(14.5): E3114: There is no identifier named 'Socket' accessible in this
scope. Did you mean 'Socket' (as in Uno.Net.Sockets.Socket)? For example, try ad
ding 'using Uno.Net.Sockets;' to the top of the code file. Could you be missing
a package reference?`
`sock.uno(14.5): E3114: There is no identifier named 'Socket' accessible in this
scope. Did you mean 'Socket' (as in Uno.Net.Sockets.Socket)? For example, try ad
ding 'using Uno.Net.Sockets;' to the top of the code file. Could you be missing
a package reference?`

Hello.
I try 'fuse build --target=Android' but found not 'Sockets' from 'Uno.Net'
Do you know this problem?

ps. local preview(on PC) is no problem. 'fuse preview'
This problem is only build android or ios.

Thank you.

**Comment by solisoft** [comment]
Add "Uno.Net.Sockets" in your .unoproj file, I'll add it and I'll fix documentation
````
"Packages": [
    "Uno.Net.Sockets",
  	"Fuse",
  	"FuseJS"
  ],
````
